---
# The title of your mod. Choose a short and descriptive name
title: Jabberwocky Stealthchanger NH36 Mount
# A short description of your mod. Try to describe your mod with 1-2 short sentences
description: This was designed to properly mount the NiteHawk36 to the Jabberwocky Toolhead while using the Stealtchanger backplate and optical sensor.  This is a remix of UserMods/TheSin-/PCB36_Mount/PCBMount.stl and is intended to be used with UserMods/Nic335/NH36Sock/SplitSock.3mf
# Mod version: Set this to 1 when you are submitting a new mod. When you make changes to your mod, you may increment this number
mod_version: 1
# You may add your discord username here so people can contact you about your mod
discord_username: Mr.Splott V2.7189
# The CAD files for your mod. Please provide them as a list.
# Note that each mod must include at least one CAD file.
cad:
- CAD/Jabberwocky_Stealthchanger_NH36_Mount_and_Spacer.step
# The image files provided with your mod. These may be instructions you use in your README.md file, or other additional pictures.
# **Note that the first image specified here will be used as cover image on mods.vorondesign.com**
# All paths are relative to this .metadata.yml file.
images:
- Images/photo.jpg
- Images/CAD.png
# List all STL files
stl:
- Jabberwocky_Stealthchanger_NH36_Mount.stl
- Jabberwocky_Stealthchanger_NH36_Mount_Spacer.stl

